# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Письмо')),
                ('status', models.CharField(choices=[('AC', 'Свободен'), ('MD', 'На расмотрение'), ('DC', 'Забронирован')], default='AC', max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Письма',
                'verbose_name': 'Письмо',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название организации')),
                ('street_address', models.CharField(max_length=350, verbose_name='Адрес организации')),
                ('phone', models.IntegerField(max_length=20, verbose_name='Номер телеофна организации')),
            ],
            options={
                'verbose_name_plural': 'Организации',
                'verbose_name': 'Организация',
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='webapp.Organization'),
        ),
    ]
