# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телеофна организации'),
        ),
    ]
