# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171201_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=180, verbose_name='Номер телеофна организации'),
        ),
    ]
