# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171201_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SantaClaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='santa_clauses', to='webapp.Letter')),
            ],
            options={
                'verbose_name': 'Дед Мороз',
                'verbose_name_plural': 'Дед Морозы',
            },
        ),
    ]
