# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_santaclaus_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='santaclaus',
            name='comments_by_santa',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий от Деда Мороза'),
        ),
        migrations.AlterField(
            model_name='santaclaus',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
