# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20171206_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='letter',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
