# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171214_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
    ]
