# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_letter_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО'),
        ),
    ]
