# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20171214_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='birthday',
        ),
    ]
