# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 12:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20180219_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='awesome_ckeditor'),
        ),
    ]
