# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180219_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contents', verbose_name='Изображение')),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_content_images', to='webapp.HomeContent')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
