# Generated by Django 2.1.3 on 2018-11-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_homecontentimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='webapp.Organization'),
        ),
    ]
