# Generated by Django 2.1.3 on 2018-11-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20181123_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='date_create',
            field=models.DateField(default='2017-12-25', verbose_name='Дата создании'),
            preserve_default=False,
        ),
    ]
