# Generated by Django 2.1.3 on 2018-11-23 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_letter_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создании'),
        ),
    ]
