# Generated by Django 2.1.3 on 2018-12-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20181123_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('AC', 'Свободен'), ('MD', 'На расмотрение'), ('DC', 'Забронирован'), ('AD', 'Принят')], default='AC', max_length=2, verbose_name='Статус'),
        ),
    ]
